language: ruby
rvm:
- 2.1
script: gitbook build && htmlproof ./_book

# branch whitelist
#branches:
#  only:
#  - gh-pages      # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true   # speeds up installation of html-proofer