sudo: false

language: bash

services:
  - docker

# Install the Docker Container
install:
  - docker pull ellerbrock/link-checker

# Add your Site or Files to Check
script:
  - docker run ellerbrock/link-checker https://dev.px4.io/en/
  - docker run ellerbrock/link-checker https://docs.px4.io/en/
  - docker run ellerbrock/link-checker https://docs.qgroundcontrol.com/en/
  - docker run ellerbrock/link-checker https://dev.qgroundcontrol.com/en/
  - docker run ellerbrock/link-checker https://mavlink.io/en/
  - docker run ellerbrock/link-checker https://docs.dronecore.io/en/
  
  
# Notification Setup
notifications:
  email:
    on_success: never
    on_failure: always